title: Once Upon a Louis Prima
author: yezzir
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I made a big fat dookie poop.

github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
